### ISSUE TITLE
Support multiple SKUs in yml files

### ISSUE THREAD

**Issue by cbrake** [git-plm/gitplm#31]
It would be handy to be able to generate assembly BOMs for multiple product SKUs -- perhaps one assembly has a termination resistor, and another does not. 

* PCA-010-0001: version 1 without termination resistor
* PCA-010-0101: version 1 with termination resistor
* PCA-010-0002: version 2 without termination resistor
* PCA-010-0102: version 2 with termination resistor

The syntax of the [BOM modification file](https://github.com/git-plm/gitplm/blob/main/example/cad-design/PCB-019.yml) could be expanded to generate multiple SKUs. Perhaps something like:

```yml
# applied to all skews
- name: modifications for all skews
  remove:
    - cmpName: Test point
    - cmpName: Test point 2
    - ref: D12
  add:
    - cmpName: "screw #4,2"
      ref: S3
      ipn: SCR-002-0002

# generate special SKU with ferrite bead
- name: 
  varBase: 0100  # adds 0100 to variation number and generates an additional BOM
  add:
    - cmdName: "Ferrite Bead"
      ipn: FER-003-1123
```
